GET /listings HTTP/1.1
Host: localhost:8080

###

POST /listings HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "poster_name": "Gene Block",
    "price": 100,
    "location": "Epicuria"
}

###